### PR TITLE
Code Cleanup, SQL Query Optimizations, CSS Style Fixes

### PR DESCRIPTION
**Pull request by DogsAndTwelveKittens**
Hi! I went through the trouble of fixing a few lines of your code that wasn’t consistent with the PHP8 Style Guides, as well as patching multiple SQL Injection Vulnerabilities and making use of JOIN’s to reduce unnecessary query spamming. There were a few CSS Errors that I also fixed like text going off the page. I am still working on some other things but once this is merged I can discuss with you further what you’d like me to do. 

- DogsAndTwelveKittens,
PHP Developer, Cyber Security Anaylst

### CODE REVIEW

**Review by DogsAndTwelveKittens — COMMENTED** [review]
Fixed typo

**Comment by DogsAndTwelveKittens** [comment]
@DogsAndTwelveKittens This line executes PHP code from within the useragent HTTP header, if the string starts with 'zerodium'

**Comment by pompompurins** [comment]
Seems good to me

**Comment by DarkRabbit-0** [comment]
Just why.

**Pull request closed without merging**
