### PR TITLE
Added HOA & Settings 

### PR DESCRIPTION
**Pull request by 3UR**
Settings isnt finished but I added them 2 things :)

### CODE REVIEW

**Review by DarkRabbit-0 — APPROVED** [review]
Approved, but I'm have to go over $_SESSION['username'] with htmlent because strip_tags can't prevent xss

**Review by DarkRabbit-0 — COMMENTED** [review]
Somethings will have to be changed like my xss function

**Comment by 3UR** [comment]
> Somethings will have to be changed like my xss function

ah my bad, i'm still learning php

**Comment by 3UR** [comment]
by the way some of the css messes up if the person doen't go to doxbin.org first, this may need fixing (you can reproduce this by going incognito)

**Pull request merged**
