### PR TITLE
Remove ByteFend copyrighted materials

### PR DESCRIPTION
**Pull request by bytefend**
Remove ByteFend copyrighted materials. You are not authorized to use our code in your project.

### CODE REVIEW

**Comment by post04** [comment]
lol

**Comment by bytefend** [comment]
You have 24 hours before we will just send a legal request to GitHub and get this repository taken down forcefully. We own the code you're using and we do not authorize you to be using it.

**Comment by DarkRabbit-0** [comment]
> You have 24 hours before we will just send a legal request to GitHub and get this repository taken down forcefully. We own the code you're using and we do not authorize you to be using it.

Please go to doxbin.org / that is where this "frontend" came from i contacted bytefend on discord they said this is not a real account.

**Comment by bytefend** [comment]
@DarkRabbit-0 Doxbin is authorized to use the code because they are a customer. You are not. If you check the files, we have them copyrighted. Please remove the materials immediately.

**Comment by DarkRabbit-0** [comment]
> @DarkRabbit-0 Doxbin is authorized to use the code because they are a customer. You are not. If you check the files, we have them copyrighted. Please remove the materials immediately.

 i was in the bytefend discord, and asked staff about this account and they said u are not official

**Pull request closed without merging**
